development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rails_aluminum_api_development
  pool: 5
  username: root
  password: root 
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rails_aluminum_api_test
  pool: 5
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rails_aluminum_api_production
  pool: 5
  username: root
  password: root
  host: localhost
